name = "github-contrib-api"
main = "src/index.js"
compatibility_date = "2024-11-29"

# Optional: configure custom routes later in Cloudflare dashboard
# routes = [ { pattern = "example.com/api/*", zone_name = "example.com" } ]
